global:
  external_labels:
    p8s_logzio_name: 'logz'
scrape_configs:
  - job_name: ecs
    file_sd_configs:
      - files:
          - /output/ecs_file_sd.yml
        refresh_interval: 1m
        
remote_write:
 - url: https://listener.logz.io:8053
   bearer_token: 'OUGaycqbyrsKRekKaAOdVKnkDcrNJvbp'
   remote_timeout: 30s
   queue_config:
     batch_send_deadline: 5s
     max_shards: 10
     min_shards: 1
     max_samples_per_send: 500
     capacity: 10000
